### ISSUE TITLE
Problem in run on windows 64 bit

### ISSUE THREAD

**Issue by myalexer** [google/gxui#130]
Hello
i try to run examples but it return this error : 

panic: APIUnavailable: WGL: The driver does not appear to support OpenGL

goroutine 1 [running, locked to thread]:
github.com/google/gxui/drivers/gl.newViewport(0xc0820042e0, 0x320, 0x258, 0x7e1
70, 0x5, 0x0, 0xc082123e80)
        E:/workspace/src/github.com/google/gxui/drivers/gl/viewport.go:81 +0x1f

github.com/google/gxui/drivers/gl.func┬╖019()
        E:/workspace/src/github.com/google/gxui/drivers/gl/driver.go:196 +0x6d
github.com/google/gxui/drivers/gl.func┬╖012()
        E:/workspace/src/github.com/google/gxui/drivers/gl/driver.go:61 +0x36
github.com/google/gxui/drivers/gl.(*driver).driverLoop(0xc0820042e0)
        E:/workspace/src/github.com/google/gxui/drivers/gl/driver.go:82 +0x7c
github.com/google/gxui/drivers/gl.StartDriver(0xc275c8)
        E:/workspace/src/github.com/google/gxui/drivers/gl/driver.go:51 +0x2c0
main.main()
        E:/workspace/src/github.com/google/gxui/samples/lists/main.go:169 +0x31

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive]:
github.com/google/gxui/drivers/gl.(*driver).syncDriver(0xc0820042e0, 0xc08219ae
0)
        E:/workspace/src/github.com/google/gxui/drivers/gl/driver.go:62 +0x137
github.com/google/gxui/drivers/gl.(*driver).CreateWindowedViewport(0xc0820042e0
 0x320, 0x258, 0x7e1c70, 0x5, 0x0, 0x0)
        E:/workspace/src/github.com/google/gxui/drivers/gl/driver.go:201 +0x1e1
github.com/google/gxui/mixins.(*Window).Init(0xc0821acd80, 0x1289808, 0xc0821ac
80, 0x1282328, 0xc0820042e0, 0x320, 0x258, 0x7e1c70, 0x5)
        E:/workspace/src/github.com/google/gxui/mixins/window.go:124 +0xd0d
github.com/google/gxui/themes/dark.CreateWindow(0xc0821a8000, 0x320, 0x258, 0x7
1c70, 0x5, 0x0, 0x0)
        E:/workspace/src/github.com/google/gxui/themes/dark/window.go:18 +0x139
github.com/google/gxui/themes/dark.(*Theme).CreateWindow(0xc0821a8000, 0x320, 0
258, 0x7e1c70, 0x5, 0x0, 0x0)
        E:/workspace/src/github.com/google/gxui/themes/dark/theme.go:177 +0x69
main.appMain(0x1282328, 0xc0820042e0)
        E:/workspace/src/github.com/google/gxui/samples/lists/main.go:160 +0x1d

github.com/google/gxui/drivers/gl.func┬╖011()
        E:/workspace/src/github.com/google/gxui/drivers/gl/driver.go:49 +0x69
github.com/google/gxui/drivers/gl.(*driver).applicationLoop(0xc0820042e0)
        E:/workspace/src/github.com/google/gxui/drivers/gl/driver.go:100 +0x72
created by github.com/google/gxui/drivers/gl.StartDriver
        E:/workspace/src/github.com/google/gxui/drivers/gl/driver.go:50 +0x2ad

i don't know how to solved this problem
please help me

**Comment by shurcooL** [comment]
Hi @myalexer,

Can you please post a little more information about your setup, that will make resolving this issue easier.

- What version of Go are you running?
- What version of Windows are you running? You mentioned it's 64 bit, but is it Windows Vista, 7, 8, 8.1?
- What commit of `gxui` do you have? The latest right now is a292a3d0d4ba55b1cec6bb08017cef2ed4977549.

**Comment by myalexer** [comment]
Thanks , sorry for little information
Go version : 
go version go1.4.2 windows/amd64

gcc version:
gcc (tdm64-1) 4.9.2

my os : 
windows 7 - 64 bit

**Comment by shurcooL** [comment]
Thanks, what commit of `gxui` are you on?

**Comment by markb007** [comment]
HI

I had same issue today .. gxui version 0.1

Regards
Mark

**Comment by markb007** [comment]
Hi

I have the same issue when I tried out the 'samples' today

Running on Windows 8.1 Pro
Go 1.4.2
TDM-GCC-64
gxui commit 37777050f35a11a72d7d8bbfc52f34a2ae7232b2


Regards
Mark

**Comment by shurcooL** [comment]
That's the latest commit and it should work.

Can you please try two older commits, specifically a292a3d0d4ba55b1cec6bb08017cef2ed4977549 and 51a2d4dfd9cbe93c774d2a72f39f4b52f466d804?

If one of those works, then this must be related to the recent GL/GLFW package changes. Otherwise, the issue must be elsewhere.

Also, can you please verify you have the latest versions of all dependencies? If you have [`gostatus` binary](https://github.com/shurcooL/gostatus#gostatus-), you can run this command and paste its output:

```bash
# Show status of all dependencies (recursive) of gxui.
go list -f '{{join .Deps "\n"}}' github.com/google/gxui/... | gostatus --stdin -v
```

Output should be like this:

```bash
     github.com/google/gxui/...
     code.google.com/p/freetype-go/...
     github.com/go-gl/gl/...
     github.com/go-gl/glfw/...
     github.com/goxjs/glfw/...
     github.com/goxjs/gl/...
     golang.org/x/tools/...
```

(If there are any characters prefixes, then something is not clean or out of date.)

**Comment by markb007** [comment]
I'd say after much testing that my graphics card does not support opengl as i ran on another machine successfully ... sorry about that .. Regards Mark

**Comment by Arnold1** [comment]
i want to test gxui on windows 7 x64 and get the following error...any idea?
```
arnold MSYS ~/gxui/samples/hello_world
$ go get -u github.com/google/gxui/...
go: missing Mercurial command. See http://golang.org/s/gogetcmd
package github.com/google/gxui
        imports github.com/google/gxui/interval
        imports github.com/google/gxui/math
        imports github.com/google/gxui/drivers/gl
        imports code.google.com/p/freetype-go/freetype/raster: exec: "hg": executable file not found in %PATH%
package github.com/google/gxui
        imports github.com/google/gxui/interval
        imports github.com/google/gxui/math
        imports github.com/google/gxui/drivers/gl
        imports code.google.com/p/freetype-go/freetype/truetype
        imports code.google.com/p/freetype-go/freetype/truetype
        imports code.google.com/p/freetype-go/freetype/truetype: cannot find package "code.google.com/p/freetype-go/freetype/truetype" in any of:
        C:\Go\src\code.google.com\p\freetype-go\freetype\truetype (from $GOROOT)
        C:\Gopath\src\code.google.com\p\freetype-go\freetype\truetype (from $GOPATH)


arnold MSYS ~/gxui/samples/hello_world
$ which hg
/usr/bin/hg

arnold MSYS ~/gxui/samples/hello_world
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Programs/ORANT/11.2.0.3.0/bin:/c/Program Files (x86)/Intel/iCLS Client:/c/Program Files/Intel/iCLS Client:/c/Windows/system32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/c/Go/bin:/c/Program Files/MATLAB/R2014b/runtime/win64:/c/Program Files/MATLAB/R2014b/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

**Comment by Arnold1** [comment]
```
$ go get -u github.com/google/gxui/...
# github.com/go-gl/gl/v2.1/gl
/usr/lib/gcc/x86_64-pc-msys/4.9.2/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-msys/4.9.2/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status
# github.com/go-gl/glfw/v3.1/glfw
In file included from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw_win32_window.c:2:0:
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c: In function ‘restoreCursor’:
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:97:45: warning: passing argument 2 of ‘LoadCursorW’ from incompatible pointer type
                 SetCursor(LoadCursorW(NULL, IDC_ARROW));
                                             ^
In file included from /usr/include/w32api/windows.h:72:0,
                 from /usr/include/w32api/GL/gl.h:13,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/../include/GLFW/glfw3.h:153,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/internal.h:63,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:28,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw_win32_window.c:2:
/usr/include/w32api/winuser.h:3955:29: note: expected ‘LPCWSTR’ but argument is of type ‘CHAR *’
   WINUSERAPI HCURSOR WINAPI LoadCursorW(HINSTANCE hInstance,LPCWSTR lpCursorName);
                             ^
In file included from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw_win32_window.c:2:0:
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c: In function ‘translateCursorShape’:
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:109:13: warning: return from incompatible pointer type
             return IDC_ARROW;
             ^
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:111:13: warning: return from incompatible pointer type
             return IDC_IBEAM;
             ^
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:113:13: warning: return from incompatible pointer type
             return IDC_CROSS;
             ^
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:115:13: warning: return from incompatible pointer type
             return IDC_HAND;
             ^
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:117:13: warning: return from incompatible pointer type
             return IDC_SIZEWE;
             ^
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:119:13: warning: return from incompatible pointer type
             return IDC_SIZENS;
             ^
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c: In function ‘_glfwRegisterWindowClass’:
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:760:42: warning: passing argument 2 of ‘LoadCursorW’ from incompatible pointer type
     wc.hCursor       = LoadCursorW(NULL, IDC_ARROW);
                                          ^
In file included from /usr/include/w32api/windows.h:72:0,
                 from /usr/include/w32api/GL/gl.h:13,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/../include/GLFW/glfw3.h:153,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/internal.h:63,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:28,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw_win32_window.c:2:
/usr/include/w32api/winuser.h:3955:29: note: expected ‘LPCWSTR’ but argument is of type ‘CHAR *’
   WINUSERAPI HCURSOR WINAPI LoadCursorW(HINSTANCE hInstance,LPCWSTR lpCursorName);
                             ^
In file included from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw_win32_window.c:2:0:
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:770:36: warning: passing argument 2 of ‘LoadIconW’ from incompatible pointer type
         wc.hIcon = LoadIconW(NULL, IDI_WINLOGO);
                                    ^
In file included from /usr/include/w32api/windows.h:72:0,
                 from /usr/include/w32api/GL/gl.h:13,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/../include/GLFW/glfw3.h:153,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/internal.h:63,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:28,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw_win32_window.c:2:
/usr/include/w32api/winuser.h:3996:27: note: expected ‘LPCWSTR’ but argument is of type ‘CHAR *’
   WINUSERAPI HICON WINAPI LoadIconW(HINSTANCE hInstance,LPCWSTR lpIconName);
                           ^
In file included from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw_win32_window.c:2:0:
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c: In function ‘_glfwPlatformSetCursor’:
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:1202:41: warning: passing argument 2 of ‘LoadCursorW’ from incompatible pointer type
             SetCursor(LoadCursorW(NULL, IDC_ARROW));
                                         ^
In file included from /usr/include/w32api/windows.h:72:0,
                 from /usr/include/w32api/GL/gl.h:13,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/../include/GLFW/glfw3.h:153,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/internal.h:63,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_window.c:28,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw_win32_window.c:2:
/usr/include/w32api/winuser.h:3955:29: note: expected ‘LPCWSTR’ but argument is of type ‘CHAR *’
   WINUSERAPI HCURSOR WINAPI LoadCursorW(HINSTANCE hInstance,LPCWSTR lpCursorName);
                             ^
# github.com/go-gl/glfw/v3.1/glfw
In file included from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw_winmm_joystick.c:2:0:
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/winmm_joystick.c: In function ‘_glfwPlatformGetJoystickName’:
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/winmm_joystick.c:173:62: warning: passing argument 1 of ‘_glfwCreateUTF8FromWideString’ from incompatible pointer type
     _glfw.winmm_js[joy].name = _glfwCreateUTF8FromWideString(jc.szPname);
                                                              ^
In file included from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/internal.h:83:0,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/winmm_joystick.c:28,
                 from C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw_winmm_joystick.c:2:
C:\Gopath\src\github.com\go-gl\glfw\v3.1\glfw\glfw/src/win32_platform.h:243:7: note: expected ‘const WCHAR *’ but argument is of type ‘CHAR *’
 char* _glfwCreateUTF8FromWideString(const WCHAR* source);
       ^
# github.com/go-gl/glfw/v3.1/glfw
/usr/lib/gcc/x86_64-pc-msys/4.9.2/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-msys/4.9.2/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status
```

**Comment by Arnold1** [comment]
im new to msys2. will i need to install mingw-w64-x86_64-gcc?

```
pacman -S mingw-w64-x86_64-gcc
```

**Comment by Arnold1** [comment]
it works fine with msys2-x86_64-20150512.exe from https://msys2.github.io/

```
pacman -S mingw-w64-x86_64-toolchain
PATH=/mingw64/bin:$PATH
```

**Comment by xeodou** [comment]
I got the same issue this morning. 
```
go version
go version go1.5 windows/386
```
I try build a windows app it crash with the same issue both 32bit and 64bit.
