### ISSUE TITLE
Errors running `go get`

### ISSUE THREAD

**Issue by jingweno** [google/gxui#3]
I'm having issues running `go get` on Yosemite:

```
$ brew list glew
/opt/boxen/homebrew/Cellar/glew/1.11.0/bin/glewinfo
/opt/boxen/homebrew/Cellar/glew/1.11.0/bin/visualinfo
/opt/boxen/homebrew/Cellar/glew/1.11.0/include/GL/ (3 files)
/opt/boxen/homebrew/Cellar/glew/1.11.0/lib/libGLEW.1.11.0.dylib
/opt/boxen/homebrew/Cellar/glew/1.11.0/lib/libGLEWmx.1.11.0.dylib
/opt/boxen/homebrew/Cellar/glew/1.11.0/lib/pkgconfig/ (2 files)
/opt/boxen/homebrew/Cellar/glew/1.11.0/lib/ (6 other files)
$  go get ./...
# github.com/go-gl-legacy/gl
In file included from ../../go-gl-legacy/gl/attriblocation.go:7:
./gl.h:2:10: fatal error: 'GL/glew.h' file not found
#include <GL/glew.h>
         ^
1 error generated.
```

**Comment by ben-clayton** [comment]
Hi jingweno,
Yes, unfortunately the go-gl-legacy/gl library (which GXUI currently depends on) has a dependency on the GLEW library. 
I can confirm GXUI runs on Windows, OSX and Linux, but the GLEW is the most difficult aspect of getting these various targets to build. I will be looking to simplify / remove this GLEW dependency in the near future.
In the meantime, please try following information on: https://github.com/go-gl-legacy/gl

**Comment by jimmykuu** [comment]
CGO_CFLAGS="-I/usr/local/Cellar/glew/1.11.0/include/GL" CGO_LDFLAGS="-L/usr/local/Cellar/glew/1.11.0/lib" go get github.com/go-gl-legacy/gl

**Comment by slimsag** [comment]
@ben-clayton Hiya (one of the authors of go-gl here) FWIW https://github.com/go-gl/gl (the bindings generated by Glow) do not depend on GLEW for this exact reason.

**Comment by nstratos** [comment]
I encountered the same problem but reached a little further. Now I am getting:
```
/tmp/go-build140376053/command-line-arguments/_obj/exe/main: error while loading shared libraries: libGLEW.so.1.12: cannot open shared object file: No such file or directory
exit status 127
```
I am using Ubuntu 14.04 64bit and I suppose it means that it doesn't know the location of the glew library to link it.

What I've done is:

* Installed glew. The make install output is:
```
install -d -m 0755 "/usr/include/GL"
install -m 0644 include/GL/wglew.h "/usr/include/GL/"
install -m 0644 include/GL/glew.h "/usr/include/GL/"
install -m 0644 include/GL/glxew.h "/usr/include/GL/"
sed \
		-e "s|@prefix@|/usr|g" \
		-e "s|@libdir@|/usr/lib64|g" \
		-e "s|@exec_prefix@|/usr/bin|g" \
		-e "s|@includedir@|/usr/include/GL|g" \
		-e "s|@version@|1.12.0|g" \
		-e "s|@cflags@||g" \
		-e "s|@libname@|GLEW|g" \
		-e "s|@requireslib@|glu|g" \
		< glew.pc.in > glew.pc
install -d -m 0755 "/usr/lib64"
install -m 0644 lib/libGLEW.so.1.12.0 "/usr/lib64/"
ln -sf libGLEW.so.1.12.0 "/usr/lib64/libGLEW.so.1.12"
ln -sf libGLEW.so.1.12.0 "/usr/lib64/libGLEW.so"
install -m 0644 lib/libGLEW.a "/usr/lib64/"
install -d -m 0755 "/usr/lib64"
install -d -m 0755 "/usr/lib64/pkgconfig"
install -m 0644 glew.pc "/usr/lib64/pkgconfig/"
```
* go get github.com/go-gl-legacy
* cd  .../gxui/samples/progress_bar
* go run main.go
```
/tmp/go-build140376053/command-line-arguments/_obj/exe/main: error while loading shared libraries: libGLEW.so.1.12: cannot open shared object file: No such file or directory
exit status 127
```

How can I tell go run to use the location of my installed glew?

**Comment by slimsag** [comment]
That error is due to `libGLEW.so.1.12` not being on your `LD_LIBRARY_PATH` (linux) .

Try `LD_LIBRARY_PATH=/path/to/glew/lib/dir go run main.go`.

**Comment by nstratos** [comment]
Alright that worked. I used:
```
LD_LIBRARY_PATH=/usr/lib64 go run main.go
```
I am trying to run one of the samples, specifically the progress_bar. What I got is:

```
libGL error: pci id for fd 4: 80ee:beef, driver (null)
OpenGL Warning: glFlushVertexArrayRangeNV not found in mesa table
OpenGL Warning: glVertexArrayRangeNV not found in mesa table
OpenGL Warning: glCombinerInputNV not found in mesa table
OpenGL Warning: glCombinerOutputNV not found in mesa table
OpenGL Warning: glCombinerParameterfNV not found in mesa table
OpenGL Warning: glCombinerParameterfvNV not found in mesa table
OpenGL Warning: glCombinerParameteriNV not found in mesa table
OpenGL Warning: glCombinerParameterivNV not found in mesa table
OpenGL Warning: glFinalCombinerInputNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterfvNV not found in mesa table
OpenGL Warning: glGetCombinerOutputParameterivNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterfvNV not found in mesa table
OpenGL Warning: glGetFinalCombinerInputParameterivNV not found in mesa table
OpenGL Warning: glDeleteFencesNV not found in mesa table
OpenGL Warning: glFinishFenceNV not found in mesa table
OpenGL Warning: glGenFencesNV not found in mesa table
OpenGL Warning: glGetFenceivNV not found in mesa table
OpenGL Warning: glIsFenceNV not found in mesa table
OpenGL Warning: glSetFenceNV not found in mesa table
OpenGL Warning: glTestFenceNV not found in mesa table
libGL error: core dri or dri2 extension not found
libGL error: failed to load driver: vboxvideo
panic: open data/SourceCodePro-Regular.ttf: no such file or directory

goroutine 18 [running]:
github.com/google/gxui/drivers/gl.(*Driver).CreateFont(0xc20807a060, 0x7591b0, 0x19, 0xc, 0x0, 0x0)
	/home/nstratos/code/go/src/github.com/google/gxui/drivers/gl/driver.go:166 +0x17d
github.com/google/gxui/themes/dark.CreateTheme(0x7fc9b3eaab18, 0xc20807a060, 0x0, 0x0)
	/home/nstratos/code/go/src/github.com/google/gxui/themes/dark/theme.go:43 +0x76
main.appMain(0x7fc9b3eaab18, 0xc20807a060)
	/home/nstratos/code/go/src/github.com/google/gxui/samples/progress_bar/main.go:19 +0x61
created by github.com/google/gxui/drivers/gl.StartDriver
	/home/nstratos/code/go/src/github.com/google/gxui/drivers/gl/driver.go:50 +0x20a

goroutine 1 [runnable, locked to thread]:
github.com/go-gl/glfw/v3.1/glfw._Cfunc_glfwWaitEvents()
	/home/nstratos/code/go/src/github.com/go-gl/glfw/v3.1/glfw/:874 +0x45
github.com/go-gl/glfw/v3.1/glfw.WaitEvents()
	/home/nstratos/code/go/src/github.com/go-gl/glfw/v3.1/glfw/window.go:642 +0x1b
github.com/google/gxui/drivers/gl.(*Driver).run(0xc20807a060)
	/home/nstratos/code/go/src/github.com/google/gxui/drivers/gl/driver.go:93 +0x81
github.com/google/gxui/drivers/gl.StartDriver(0x724090, 0x4, 0x7b1680)
	/home/nstratos/code/go/src/github.com/google/gxui/drivers/gl/driver.go:51 +0x21a
main.main()
	/home/nstratos/code/go/src/github.com/google/gxui/samples/progress_bar/main.go:52 +0x48

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2

```

**Comment by ShawnMilo** [comment]
If someone has this working, and is feeling generous, would you create a Dockerfile that builds it, perhaps using the official "golang" Docker image as the base, please? I'd like to help out where I can, and having a working environment without having to "junk up" my actual machine with various dependencies would be wonderful.

**Comment by crawshaw** [comment]
@ShawnMilo please file a separate issue for the dockerfile. It may not happen soon, but it should be tracked separately.

**Comment by ajstarks** [comment]
my build recipe (on Mac OS X)

    $ cd ~/Code
    $ git clone https://github.com/nigels-com/glew.git glew
    $ cd glew
    $ make extensions
    $ sudo make install

**Comment by ben-clayton** [comment]
@slimsag Thanks Stephen - I've updated to use v3.2-core instead.

**Comment by ben-clayton** [comment]
This should now be fixed after running:
    `go get github.com/go-gl/gl/v3.2-core/gl`
