### ISSUE TITLE
samples/image_viewer panic: open : no such file or directory

### ISSUE THREAD

**Issue by haisum** [google/gxui#41]
All other samples work great but image_viewer sample gives following error:

![selection_061](https://cloud.githubusercontent.com/assets/911409/6749830/dce5843e-cf15-11e4-85ac-13d4322b536f.png)

```
panic: open : no such file or directory

goroutine 4 [running]:
runtime.panic(0x6a6ac0, 0xc21006b000)
	/usr/lib/go/src/pkg/runtime/panic.c:266 +0xb6
main.appMain(0x7f6bed85a280, 0xc210048060)
	/home/haisum/gxgui/src/github.com/google/gxui/samples/image_viewer/main.go:26 +0x89
created by github.com/google/gxui/drivers/gl.StartDriver
	/home/haisum/gxgui/src/github.com/google/gxui/drivers/gl/driver.go:46 +0x14e

goroutine 1 [runnable]:
github.com/go-gl/glfw/v3.1/glfw._Cfunc_glfwWaitEvents(0x48b94f)
	github.com/go-gl/glfw/v3.1/glfw/_obj/_cgo_defun.c:967 +0x31
github.com/go-gl/glfw/v3.1/glfw.WaitEvents()
	/home/haisum/gxgui/src/github.com/go-gl/glfw/v3.1/glfw/window.go:642 +0x1a
github.com/google/gxui/drivers/gl.(*Driver).run(0xc210048060)
	/home/haisum/gxgui/src/github.com/google/gxui/drivers/gl/driver.go:90 +0x6f
github.com/google/gxui/drivers/gl.StartDriver(0x7f4a98)
	/home/haisum/gxgui/src/github.com/google/gxui/drivers/gl/driver.go:47 +0x15e
main.main()
	/home/haisum/gxgui/src/github.com/google/gxui/samples/image_viewer/main.go:53 +0x2c

goroutine 3 [syscall]:
runtime.goexit()
	/usr/lib/go/src/pkg/runtime/proc.c:1394
```

**Comment by nguyendangminh** [comment]
@haisum you must specify the image, like this:
$ image_viewer --file /path/to/your/image/file
As @ben-clayton mentioned, there's not much document.

**Comment by ben-clayton** [comment]
Pushed ca02943971c8512202c965f95ab030757733852f, which shows a usage, drops the --file prefix, and shows decent error messages if the file cannot be found / loaded.
