### ISSUE TITLE
example: progress_bar crashed  by occasionally  under OS X

### ISSUE THREAD

**Issue by lewgun** [google/gxui#48]
os: OS X 10.10
go version: go1.4.2 darwin/amd64

when the example: progress_bar is running, click the close button, it's crashed by occasionally with output as follows:

➜  progress_bar git:(master) go run main.go
panic: Attempting to render a destroyed Viewport

goroutine 1 [running, locked to thread]:
github.com/google/gxui/drivers/gl.(*Viewport).render(0xc20819e000)
	/Users/liu/Sources/go/the3rd/src/github.com/google/gxui/drivers/gl/viewport.go:244 +0x86
github.com/google/gxui/drivers/gl.func·044()
	/Users/liu/Sources/go/the3rd/src/github.com/google/gxui/drivers/gl/viewport.go:308 +0xae
github.com/google/gxui/drivers/gl.(*Driver).flush(0xc20801e040)
	/Users/liu/Sources/go/the3rd/src/github.com/google/gxui/drivers/gl/driver.go:73 +0x5e
github.com/google/gxui/drivers/gl.func·013()
	/Users/liu/Sources/go/the3rd/src/github.com/google/gxui/drivers/gl/driver.go:113 +0xcc
github.com/google/gxui/drivers/gl.(*Driver).run(0xc20801e040)
	/Users/liu/Sources/go/the3rd/src/github.com/google/gxui/drivers/gl/driver.go:85 +0x75
github.com/google/gxui/drivers/gl.StartDriver(0x44dee00)
	/Users/liu/Sources/go/the3rd/src/github.com/google/gxui/drivers/gl/driver.go:47 +0x1e5
main.main()
	/Users/liu/Sources/go/the3rd/src/github.com/lewgun/gxui/samples/progress_bar/main.go:50 +0x2a

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive]:
github.com/google/gxui.EventLoop(0x47b4cc8, 0xc20801e040)
	/Users/liu/Sources/go/the3rd/src/github.com/google/gxui/event_loop.go:8 +0x65
main.appMain(0x47b4cc8, 0xc20801e040)
	/Users/liu/Sources/go/the3rd/src/github.com/lewgun/gxui/samples/progress_bar/main.go:46 +0x568
created by github.com/google/gxui/drivers/gl.StartDriver
	/Users/liu/Sources/go/the3rd/src/github.com/google/gxui/drivers/gl/driver.go:46 +0x1d5
exit status 2

**Comment by ben-clayton** [comment]
Eww. This streams race condition.

**Comment by crawshaw** [comment]
With ```go build -race``` I see:

```
==================
WARNING: DATA RACE
Read by main goroutine:
  github.com/google/gxui/drivers/gl.(*refCounted).AssertAlive()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/refcounted.go:75 +0x48
  github.com/google/gxui/drivers/gl.(*Canvas).draw()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/canvas.go:57 +0x5a
  github.com/google/gxui/drivers/gl.(*Viewport).render()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/viewport.go:256 +0x381
  github.com/google/gxui/drivers/gl.(*Viewport).SetCanvas.func1()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/viewport.go:308 +0x113
  github.com/google/gxui/drivers/gl.(*Driver).run()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/driver.go:85 +0x90
  github.com/google/gxui/drivers/gl.StartDriver()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/driver.go:47 +0x300
  main.main()
      /Users/crawshaw/src/github.com/google/gxui/samples/progress_bar/main.go:50 +0x37

Previous write by goroutine 6:
  sync/atomic.AddInt32()
      /Users/crawshaw/go/src/runtime/race_amd64.s:255 +0xb
  github.com/google/gxui/drivers/gl.(*refCounted).release()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/refcounted.go:60 +0x6c
  github.com/google/gxui/drivers/gl.(*Canvas).Release()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/canvas.go:236 +0x40
  github.com/google/gxui/mixins.(*Window).Draw()
      /Users/crawshaw/src/github.com/google/gxui/mixins/window.go:92 +0x201
  github.com/google/gxui/mixins.(*Window).update()
      /Users/crawshaw/src/github.com/google/gxui/mixins/window.go:60 +0x144
  github.com/google/gxui/mixins.(*Window).(github.com/google/gxui/mixins.update)-fm()
      /Users/crawshaw/src/github.com/google/gxui/mixins/window.go:47 +0x34
  github.com/google/gxui.EventLoop()
      /Users/crawshaw/src/github.com/google/gxui/event_loop.go:9 +0x88
  main.appMain()
      /Users/crawshaw/src/github.com/google/gxui/samples/progress_bar/main.go:46 +0x5ca

Goroutine 6 (running) created at:
  github.com/google/gxui/drivers/gl.StartDriver()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/driver.go:46 +0x2f2
  main.main()
      /Users/crawshaw/src/github.com/google/gxui/samples/progress_bar/main.go:50 +0x37
==================
==================
WARNING: DATA RACE
Read by goroutine 8:
  github.com/google/gxui/themes/dark.CreateProgressBar.func1.1()
      /Users/crawshaw/src/github.com/google/gxui/themes/dark/progress_bar.go:30 +0x4a

Previous write by goroutine 6:
  github.com/google/gxui/themes/dark.(*ProgressBar).Layout()
      /Users/crawshaw/src/github.com/google/gxui/themes/dark/progress_bar.go:57 +0x33b
  github.com/google/gxui/mixins/parts.(*LinearLayout).LayoutChildren()
      /Users/crawshaw/src/github.com/google/gxui/mixins/parts/linear_layout.go:64 +0xb61
  github.com/google/gxui/mixins.(*LinearLayout).LayoutChildren()
      <autogenerated>:271 +0x5a
  github.com/google/gxui/mixins/parts.callLayoutChildrenIfSupported()
      /Users/crawshaw/src/github.com/google/gxui/mixins/parts/utils.go:14 +0x99
  github.com/google/gxui/mixins/parts.(*Layoutable).Layout()
      /Users/crawshaw/src/github.com/google/gxui/mixins/parts/layoutable.go:59 +0x60d
  github.com/google/gxui/mixins.(*LinearLayout).Layout()
      <autogenerated>:258 +0x69
  github.com/google/gxui/mixins.(*Window).LayoutChildren()
      /Users/crawshaw/src/github.com/google/gxui/mixins/window.go:100 +0x6ac
  github.com/google/gxui/themes/dark.(*Window).LayoutChildren()
      <autogenerated>:1266 +0x52
  github.com/google/gxui/mixins.(*Window).update()
      /Users/crawshaw/src/github.com/google/gxui/mixins/window.go:56 +0xf5
  github.com/google/gxui/mixins.(*Window).(github.com/google/gxui/mixins.update)-fm()
      /Users/crawshaw/src/github.com/google/gxui/mixins/window.go:47 +0x34
  github.com/google/gxui.EventLoop()
      /Users/crawshaw/src/github.com/google/gxui/event_loop.go:9 +0x88
  main.appMain()
      /Users/crawshaw/src/github.com/google/gxui/samples/progress_bar/main.go:46 +0x5ca

Goroutine 8 (running) created at:
  time.goFunc()
      /Users/crawshaw/go/src/time/sleep.go:129 +0x75

Goroutine 6 (running) created at:
  github.com/google/gxui/drivers/gl.StartDriver()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/driver.go:46 +0x2f2
  main.main()
      /Users/crawshaw/src/github.com/google/gxui/samples/progress_bar/main.go:50 +0x37
==================
==================
WARNING: DATA RACE
Write by goroutine 6:
  sync/atomic.AddInt32()
      /Users/crawshaw/go/src/runtime/race_amd64.s:255 +0xb
  github.com/google/gxui/drivers/gl.(*refCounted).release()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/refcounted.go:60 +0x6c
  github.com/google/gxui/drivers/gl.(*Canvas).Release()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/canvas.go:236 +0x40
  github.com/google/gxui/mixins/parts.(*DrawPaint).Draw()
      /Users/crawshaw/src/github.com/google/gxui/mixins/parts/draw_paint.go:73 +0x3da
  github.com/google/gxui/mixins.(*LinearLayout).Draw()
      <autogenerated>:214 +0x63
  github.com/google/gxui/mixins/parts.(*PaintChildren).PaintChild()
      /Users/crawshaw/src/github.com/google/gxui/mixins/parts/paint_children.go:38 +0x3e
  github.com/google/gxui/themes/dark.(*Window).PaintChild()
      <autogenerated>:1310 +0x8c
  github.com/google/gxui/mixins/parts.(*PaintChildren).Paint()
      /Users/crawshaw/src/github.com/google/gxui/mixins/parts/paint_children.go:31 +0x21a
  github.com/google/gxui/themes/dark.(*Window).Paint()
      /Users/crawshaw/src/github.com/google/gxui/themes/dark/window.go:26 +0xcf
  github.com/google/gxui/mixins.(*Window).Draw()
      /Users/crawshaw/src/github.com/google/gxui/mixins/window.go:89 +0x176
  github.com/google/gxui/mixins.(*Window).update()
      /Users/crawshaw/src/github.com/google/gxui/mixins/window.go:60 +0x144
  github.com/google/gxui/mixins.(*Window).(github.com/google/gxui/mixins.update)-fm()
      /Users/crawshaw/src/github.com/google/gxui/mixins/window.go:47 +0x34
  github.com/google/gxui.EventLoop()
      /Users/crawshaw/src/github.com/google/gxui/event_loop.go:9 +0x88
  main.appMain()
      /Users/crawshaw/src/github.com/google/gxui/samples/progress_bar/main.go:46 +0x5ca

Previous read by main goroutine:
  [failed to restore the stack]

Goroutine 6 (running) created at:
  github.com/google/gxui/drivers/gl.StartDriver()
      /Users/crawshaw/src/github.com/google/gxui/drivers/gl/driver.go:46 +0x2f2
  main.main()
      /Users/crawshaw/src/github.com/google/gxui/samples/progress_bar/main.go:50 +0x37
==================
```

...and more. (I have been wondering about that refcounting mechanism and if there is some other way.)

**Comment by ben-clayton** [comment]
I'm sure there is. It's a bit broken at the moment, and is on my TODO list.
