### ISSUE TITLE
panic with very big font

### ISSUE THREAD

**Issue by zhangpy** [google/gxui#97]
I'd like to show big font, e.g. show a very big letter in the whole screen. 
so I change font size from 12 to 1024.
~~~
defaultFont, err := driver.CreateFont(gxfont.Default, 1024)
~~~
I got panic
panic: runtime error: slice bounds out of range

goroutine 1 [running, locked to thread]:
github.com/google/gxui/drivers/gl.(*glyphPage).add(...)
	gopath/src/github.com/google/gxui/drivers/gl/glyph_page.go:138 +0x567
github.com/google/gxui/drivers/gl.(*glyphTable).get(...)
	...
main.main()
	gopath/src/github.com/google/gxui/samples/progress_bar/main.go:50 +0x2a

It is OK if I use 512 instead. 
How big could a font be?

**Comment by ben-clayton** [comment]
You are hitting the maximum glyph page size which is [512x512](https://github.com/google/gxui/blob/master/drivers/gl/glyph_page.go#L19). This seemed like a reasonable limit.
I have to ask, is there a good reason to change this? :)

**Comment by zhangpy** [comment]
I try to show a rune(international word or char) to occupy the almost the whole screen. 
One rune one screen.
My screen resolution is 1920x1080. 512 is OK but 768 looks better.
Maybe I could change the resolution or scale, but not sure.

**Comment by zhangpy** [comment]
The limitation comes from font file or gxui?
If possible, could we remove the limitation?

**Comment by ben-clayton** [comment]
> The limitation comes from font file or gxui?
GXUI. I've briefly [described the font rendering process here](https://github.com/google/gxui/issues/22#issuecomment-91968197).

> If possible, could we remove the limitation?

I could make a glyph page expand to fit the size of the glyph when the page is empty. In your case of enormous glyphs, this would mean each glyph would get its own page (texture), and so every giant glyph would require a separate OpenGL draw call. This would mean performance would be dire if you were to try drawing giant strings, but that doesn't sound like an issue for what you're doing.

**Comment by zhangpy** [comment]
Thanks ben. 
yes. I don't worry about the performance. I only show very few glyphs.
Please let me know if you have time to create the sample. :)

**Comment by Annonomus-Penguin** [comment]
It would be more graceful to panic with a custom message--in this case, it's not immediately apparent that it's because the font size is too big.

A simple if statement would add virtually no overhead but it would prove helpful
